# https://docs.travis-ci.com/user/customizing-the-build/
language: cpp

sudo: required

addons:
  sonarcloud:
    organization: "edisonramalut-github"
    token:
      secure: "7116cbc8a61b1ab205155c9a4c73e0d476457c10"
      
script:
  - make clean
  - build/workspaces/update-workspaces.sh --with-system-nvtt
  - build-wrapper-linux-x86-64 --out-dir bw-output make all make -C build/workspaces/gcc
  - make test
  - sonar-scanner

matrix:
  include:
# linux
    - os: linux
      compiler: gcc
# This var is only used for display
      env: Compiler_Version="4.8"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
# preceding the version with a hyphen, as it gets added to the gcc command
# when CC and CXX are exported in the "script" section below
      env: Tr_Compiler_Version="-5"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-6
          - g++-6
      env: Tr_Compiler_Version="-6"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-7
          - g++-7
      env: Tr_Compiler_Version="-7"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-8
          - g++-8
      env: Tr_Compiler_Version="-8"
# clang
    - os: linux
      compiler: clang
      env: Compiler_Version="5"
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
          packages:
          - clang-6.0
      env: Tr_Compiler_Version="-6.0"
# When using the build-osx-libs.sh script, the job exceeds 50 minutes,
# which is the limit for running a test on Travis. Build terminates.
#
# osx
#
#    - os: osx
#      osx_image: xcode9.2
#      env: Tr_Xcode_Version="9.2"
#    - os: osx
#      osx_image: xcode9.3beta
#      env: Tr_Xcode_Version="9.3beta"

before_install:
sudo add-apt-repository -y ppa:wfg/0ad
sudo apt-get update
sudo apt-get install -q -y libsodium-dev libgloox-dev libenet-dev libboost1.58-dev libboost-filesystem1.58-dev
sudo apt-get install -q libegl1-mesa-dev libgles2-mesa-dev
sudo apt-get install -q libcurl4-gnutls-dev libicu-dev libminiupnpc-dev libnspr4-dev libnvtt-dev libogg-dev libopenal-dev libpng-dev libsdl2-dev libvorbis-dev libwxgtk3.0-dev libxcursor-dev libxml2-dev zlib1g-dev
